---
title: "Problem Set 2"
Name: "Runci Hu"
date: "2022-09-23"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyquant)
library(ggplot2)
```

##Fuel Economy
##!
```{r}
vehicles <- read.csv("~/Desktop/vehicles.csv", header = TRUE)
vehicles$phevBlended <- as.logical(vehicles$phevBlended)
sub1 <- subset(vehicles,phevBlended == FALSE)
Fuelcar <- subset(sub1, highwayE==0)

ggplot(data = Fuelcar, aes(y=fuelCost08, x=year)) + geom_point(size=1) + geom_smooth(col="red", method ="loess", se = FALSE) + labs(title = "Fuel Cost changes per year", y= "fuel cost 08", x= "year")
## The line has a downward tendency. It shows that flue costs is getting lower. 
```

##2
```{r}
carmaker <- subset(Fuelcar, make== c("Honda","Mercedes-Benz", "Porsche", "Lexus"))

ggplot(data=carmaker, aes(x=year,y=barrels08,color=make, group=make)) +
  geom_line() + labs(title = "Barrels changes of petroleum per year", y= "barrels08", x= "year")
## For these 4 makers, Honda has the lowest barrels changes of petroleum per year. 

ggplot(data=carmaker, aes(x=year,y=highway08, color=make, group=make)) +
  geom_line() + labs(title = "Highway MPG per year", y= "highway08", x= "year")
## For these 4 makers, Honda has the highest highway MPG.

##barrels08 shows annual petroleum consumption in barrels, in which lower is better
##highway08 is the highway MPG of cars that higher implies efficiency.
##In conclusion, Honda makes the most progress.
```

##NASDAQ Composite
```{r}
IXIC21.22 <- read.csv("~/Desktop/IXIC21-22.csv")
x <- as.Date(IXIC21.22$Date)
y <- IXIC21.22$Adj.Close
ggplot(data=IXIC21.22, aes(x, y)) + geom_candlestick(aes(open = Open, high = High, low = Low, close = Close)) + labs(title = "NASDAQ Composite Candlestick Chart", y = "Adj.Clost", x = "Data") + theme_tq()

##The candlestick plot shows the adjusted cost for composite in each month, 
##the tendency is generally decreasing. 
```



##Rural Capacity Index
##1
```{r}
data<-read.csv("ruralCapacityData.csv")
rcd <- subset(data, County!= "Bernalillo County")
```

```{r}
x <- rcd$per_over_25_with_bach
y <- rcd$cap_index
ggplot(data=rcd, aes(x, y)) + geom_point() + labs(title = "Rural Capacity Index Plot", y = "cap index", x="per over 25 bach") + geom_smooth(col="red") + theme_tq()

##The plot indicates the relation between cap index and 
##percentage people over 25 years old with bachelor degree. 
##The slope is positive.   
```

##2
```{r}
m <- rcd$house_broadband
x <- rcd$per_over_25_with_bach
y <- rcd$cap_index
ggplot(data = rcd, aes(x,m, color= y)) + geom_point(size=5) + labs(title = "Relation Plot", y = "house broadband", x="per over 25 with bach")

##The gradation of the color blue represents cap index. 
##The lighter the color is, the higher the cap index is. 
```

##3
```{r}
data1 <- subset(rcd, pop_total < 16000)
data2 <- subset(rcd, pop_total > 16000 & pop_total < 55000)
data3 <- subset(rcd, pop_total > 55000)

ggplot(data=data1, aes(x=pop_total, y=cap_index)) + geom_point() + labs(title = "Total Population Less than 16000", y="cap index", x= "pop total") + geom_smooth(color="blue")

ggplot(data=data2, aes(x=pop_total, y=cap_index)) + geom_point() + labs(title = "Total Population More than 16000 and Less than 55000", y="cap index", x= "pop total") + geom_smooth(color="red")

ggplot(data=data3, aes(x=pop_total, y=cap_index)) + geom_point() + labs(title = "Total Population More than 55000", y="cap index", x= "pop total") + geom_smooth(color="yellow")

##These three plots shows the relation between total population and cap index. 
##The population has been divided in 3 groups, 
##in which is lower 16000, between 16000 and 55000, and over 55000. 
##And we can see that in the 3rd plot "Total Population More than 55000", 
##the average cap index is the highest. 
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
